services:
  minio:
    image: minio/minio
    container_name: music_system_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: .
      dockerfile: MusicSystem.Backend/Dockerfile
    container_name: music_system_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Minio__Endpoint=http://minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
      - Minio__BucketName=music-system-media
      - Minio__ForcePathStyle=true
      - LiveKit__ApiKey=devkey
      - LiveKit__ApiSecret=LiveKit_Secret_Key_At_Least_32_Chars_Long_Secure
      - LiveKit__ServerUrl=http://136.248.64.90/livekit/
    depends_on:
      - minio

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: music_system_lives
    ports:
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC
    environment:
      MTX_PROTOCOLS: tcp
      MTX_WEBRTCADDITIONALHOSTS: 0.0.0.0

  livekit:
    image: livekit/livekit-server:latest
    container_name: music_system_livekit
    command: --config /etc/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      LIVEKIT_KEYS: "devkey: LiveKit_Secret_Key_At_Least_32_Chars_Long_Secure"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro

  nginx:
    image: nginx:latest
    container_name: music_system_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - backend
      - minio
      - livekit

volumes:
  minio_data:
  nginx_cache:
