name: music_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.103+57

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  get_it: ^9.2.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_messaging: ^16.1.0
  firebase_storage: ^13.0.5
  cloud_functions: any
  google_fonts: ^7.0.0
  flutter_animate: ^4.5.2
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  uuid: ^4.5.2
  intl: ^0.20.2
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  file_picker: any
  excel: ^4.0.6
  confetti: ^0.8.0
  http: ^1.6.0
  responsive_framework: ^1.5.1
  share_plus: ^12.0.1
  printing: ^5.14.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  html: ^0.15.6
  flutter_typeahead: ^5.2.0
  rxdart: ^0.28.0
  video_player: ^2.10.1
  livekit_client: ^2.5.0
  google_sign_in: ^6.2.1
  table_calendar: ^3.2.0
  audioplayers: ^6.1.1
  record: ^6.1.1
  flutter_web_plugins:
    sdk: flutter
  pro_image_editor: ^11.17.0
  url_launcher: ^6.3.2
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  mockito: ^5.6.3
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/images/
